# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0004_on_delete_arg'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='app',
            field=models.CharField(blank=True, choices=[('', '-----'), ('press', 'Press'), ('blog', 'Blog')], db_index=True, default='', max_length=5, verbose_name='application'),
        ),
    ]
