# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0004_on_delete_arg'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='language',
            field=models.CharField(blank=True, choices=[('', '---'), ('en', 'English'), ('ar', 'Arabic')], db_index=True, default='', max_length=20, verbose_name='language'),
        ),
    ]
