# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0005_entry_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='language',
            field=models.CharField(blank=True, choices=[('', '---'), ('en', 'English'), ('ar', 'Arabic')], db_index=True, default=django.utils.translation.get_language, max_length=20, verbose_name='language'),
        ),
    ]
