# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0005_entry_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='app',
            field=models.CharField(blank=True, choices=[('', '-----')], db_index=True, default='', max_length=50, verbose_name='application'),
        ),
    ]
